name: Tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - run: ruby main.rb
      env:
        FILENAME: test.txt
